#!/bin/bash
python delete_migrations.py
cd backend
python manage.py makemigrations
python manage.py migrate
echo Loading data for teams...
python manage.py loaddata teams.json
echo Loading data for seasons...
python manage.py loaddata seasons.json
echo Loading data for player positions...
python manage.py loaddata playerpositions.json
echo Loading data for player stats...
python manage.py loaddata players.json
echo Loading data for player seasons...
python manage.py loaddata playerseasons.json
echo Loading data for team seasons...
python manage.py loaddata teamseasons.json
echo Loading data for games...
python manage.py loaddata games.json
echo Loading data for team games...
python manage.py loaddata teamgames.json